---
ssh_canonical_domains:
  - grnoc.iu.edu

ssh_host_configs:
  # oob devices
  oob-ak23 oob-ak23-1:
    Hostname: oob.ak23.bldc.grnoc.iu.edu
    Ciphers: aes256-cbc
    KexAlgorithms: diffie-hellman-group1-sha1
  oob-bc10 oob-bc10-1:
    Hostname: oob.bc10.bldc.grnoc.iu.edu
    Ciphers: aes256-cbc
    KexAlgorithms: diffie-hellman-group1-sha1
  oob-bc10-2:
    Hostname: oob.bc10.bldc.grnoc.iu.edu
    Ciphers: aes256-cbc
    KexAlgorithms: diffie-hellman-group1-sha1
  oob-n13:
    Hostname: oob.n13.ctc.grnoc.iu.edu
    Ciphers: aes256-cbc
    KexAlgorithms: diffie-hellman-group1-sha1

  # pdu devices
  pdu-bc10:
    User: grnoc
    Hostname: 10.240.3.15
    Ciphers: aes256-cbc
    HostKeyAlgorithms: ssh-dss
    KexAlgorithms: diffie-hellman-group1-sha1
  pdu-n13:
    User: grnoc
    Hostname: 10.241.3.54
    Ciphers: aes256-cbc
    HostKeyAlgorithms: ssh-dss
    KexAlgorithms: diffie-hellman-group1-sha1
