---
bash_aliases:
  del_backups: find . -type f -name '*~' -exec rm {} +
  fix_perms: find . -type f -exec chmod 644 {} \; ; find . -type d -exec chmod 755 {} \;
  ls: ls --color=auto
  ll: ls -l --color=auto
  ipt: sudo iptables --line-numbers -nvL
  ip6t: sudo ip6tables --line-numbers -nvL
  ssh_kill: pkill -f .ssh/cp-$(whoami)@

bash_functions:
  config_host:
    - name=$1
    - shift
    - ansible-playbook playbook.yml -e "targets=$name" "$@"
  del_known_host:
    - LINE_NUMBER=$1
    - "[[ ! -z $LINE_NUMBER ]] && sed -i -e $1d ~/.ssh/known_hosts"
